### ISSUE TITLE
目前透過 UI 設定，層級有辦法改全域嗎？

### ISSUE THREAD

**Issue by jakeuj** [EasyAbp/Abp.SettingUi#114]
目前設定後 [ProviderName] 是 T，但我想改 G，看這邊文檔好像沒提到這部分，想確認一下是否有相關功能，謝謝

**Comment by gdlcf88** [comment]
https://github.com/EasyAbp/Abp.SettingUi/blob/42a639bc918184bad67194a27565012d97db8a3c/src/EasyAbp.Abp.SettingUi.Application/SettingUiAppService.cs#L190-L192

Setting UI manages global-level or tenant-level setting values by default. If it updated user-level setting values, check that the `SettingDefinition.Providers` contains `UserSettingValueProvider.ProviderName`, see:
https://github.com/EasyAbp/Abp.SettingUi/blob/42a639bc918184bad67194a27565012d97db8a3c/src/EasyAbp.Abp.SettingUi.Application/SettingUiAppService.cs#L180-L183

**Comment by jakeuj** [comment]
> https://github.com/EasyAbp/Abp.SettingUi/blob/42a639bc918184bad67194a27565012d97db8a3c/src/EasyAbp.Abp.SettingUi.Application/SettingUiAppService.cs#L190-L192
> 
> Setting UI manages global-level or tenant-level setting values by default. If it updated user-level setting values, check that the `SettingDefinition.Providers` contains `UserSettingValueProvider.ProviderName`, see:
> 
> https://github.com/EasyAbp/Abp.SettingUi/blob/42a639bc918184bad67194a27565012d97db8a3c/src/EasyAbp.Abp.SettingUi.Application/SettingUiAppService.cs#L180-L183

看了一下源碼，看來是要先加 `.WithProviders(GlobalSettingValueProvider.ProviderName)`

https://github.com/abpframework/abp/blob/7d7526544f124a4af319a4199f2ec8779fc26b75/framework/src/Volo.Abp.Settings/Volo/Abp/Settings/SettingDefinition.cs#L95-L103

我看官方文件好像沒有提到 WithProperty 與 WithProviders 的樣子

我在試試看，謝謝!
