### ISSUE TITLE
Usage with MultiTenancy

### ISSUE THREAD

**Issue by Znow** [EasyAbp/Abp.SettingUi#12]
Hi, just started using your module, its awesome! 

What is the roadmap for implementing the tenant provider and giving ability to control settings for tenants?

Thanks

**Comment by gdlcf88** [comment]
Did you mean a host-side admin controlling tenant's setting values? If so, you should not do that, the host is not the master of tenants, please think of it as a tenant without TenantId.

**Comment by Znow** [comment]
No, what I mean is tenants themself controlling the setting ontop of users. So the tenant "admins" can control the settings, which will be inherited by the users.

**Comment by gdlcf88** [comment]
Got it. I think you found a bug.

Hi @wakuflair, I try to grant the setting UI's permission to a tenant-side user, when he changes a setting value, his behavior affects the global setting value:
![image](https://user-images.githubusercontent.com/30018771/84773745-727cc900-b00f-11ea-8a0b-beac26a3aef5.png)

The expected result is that a tenant-side setting data is created, is that so?

**Comment by Znow** [comment]
As far as I have seen, the settings are also global for all users, so is this intended, or actual missing stuff or a bug? :D

**Comment by wakuflair** [comment]
Hi guys
Yes the settings value are set by using "global", for now.
Other scopes(Tenant, User, eg.) are on the roadmap.

**Comment by gdlcf88** [comment]
For now, an admin user (from host or one of tenants) can grant the setting management permission himself and control the global values. It is dangerous!

**Comment by gdlcf88** [comment]
About the user-side setting values management, I have these ideas:

* Provide a dedicated page and permission for users to control the setting values for themself.
* Show only the setting items with `IsVisibleToClients == true`.

**Comment by gdlcf88** [comment]
> Maybe SettingUI could provide extra permission and page to manage the global setting values. (the permission is tenant-only, of course).

After some consideration, I think the global setting management feature is not reasonable to exist. If an app admin wants to manage a global setting value, he can change the default value or implement the global values management feature himself. All in all, we should not provide an unreasonable design.

**Comment by wakuflair** [comment]
> he can change the default value or implement the global values management feature himself

Of course he can. But SettingUI is supposed to provide an easy way to set settings value.

For example: An admin wants to set the theme of the entire website through UI.

**Comment by gdlcf88** [comment]
> For example: An admin wants to set the theme of the entire website through UI.

Then he changes the setting value of the current tenant (for the host-side, the TenantId == null), instead of the global setting value.

**Comment by wakuflair** [comment]
Is this way available for single tenant application?

**Comment by gdlcf88** [comment]
I think so, since setting values of single-tenant apps (or host-only apps) will be affected by the setting ``ProviderName == T`` with ``ProviderKey == null``.

**Comment by wakuflair** [comment]
OK. I'll change `SetGlobalAsync` to `SetForCurrentTenantAsync`
