### ISSUE TITLE
上传到正式环境报错

### ISSUE THREAD

**Issue by csr2** [EasyAbp/Abp.SettingUi#13]
![1111111](https://user-images.githubusercontent.com/12671474/84609504-d5744000-aee9-11ea-9987-ae078041dea7.png)

**Comment by wakuflair** [comment]
Hi 
Which version of the SettingUI you are using?

**Comment by csr2** [comment]
1.0.7

**Comment by csr2** [comment]
可以设置成根据每个用户获取设置吗

**Comment by wakuflair** [comment]
> 可以设置成根据每个用户获取设置吗

See https://github.com/EasyAbp/Abp.SettingUi/issues/12#issuecomment-645099729

> 1.0.7

Is anything OK now?

**Comment by wakuflair** [comment]
Close since no response for long time.
