### ISSUE TITLE
Change theme layout

### ISSUE THREAD

**Issue by Znow** [EasyAbp/Abp.SettingUi#30]
Hi

How can I change the theme layout for this module?

Thanks

**Comment by wakuflair** [comment]
Hi you can use ABP's [Virtual File System](https://docs.abp.io/en/abp/latest/Virtual-File-System) to custom layout for SettingUI.
The target file is [Default.cshtml](https://github.com/EasyAbp/Abp.SettingUi/blob/6bc556d7b2cec5cd0a664f648d3c647df7b5d853/src/EasyAbp.Abp.SettingUi.Web/Pages/Components/Default.cshtml)

ABP also has a helpful guide for customization:
https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface

**Comment by Znow** [comment]
@wakuflair 

I need to know the folder for where the Default.cshtml should be placed in? It's not very easy to read from your setup

**Comment by wakuflair** [comment]
Hi Znow
The folder can be clearly seen from the source.

**Comment by Znow** [comment]
@wakuflair  Why cant you just write the folder name then? :-) That is why I am asking in the first place.

Is this the folder name then? "EasyAbp.Abp.SettingUi.Web/Pages/Components"
