### ISSUE TITLE
Complete the missing localizations

### ISSUE THREAD

**Issue by wakuflair** [EasyAbp/Abp.SettingUi#48]
There are some new settings added the sample app, we should complete the localizations.

**Comment by wakuflair** [comment]
en and zh-Hans have been added with https://github.com/EasyAbp/Abp.SettingUi/commit/29c6160e6274e4c2d98bf8653dbf9a8a8f4a11ce.

@cihangll Can you help with the tr localization?

**Comment by cihangll** [comment]
Hi @wakuflair,
I sent [PR](https://github.com/EasyAbp/Abp.SettingUi/pull/50) for this.

**Comment by wakuflair** [comment]
Resolved with #50
