### ISSUE TITLE
Projects should be depend on SettingUiApplicationContractsModule

### ISSUE THREAD

**Issue by cihangll** [EasyAbp/Abp.SettingUi#51]
Hi,
Can you add [this config](https://github.com/EasyAbp/Abp.SettingUi/blob/db0e6189fa236588c2220e02321bdf7affd34a88/sample/MyAbpApp/src/MyAbpApp.Application.Contracts/MyAbpAppApplicationContractsModule.cs#L20) in [AbpHelper.CLI](https://github.com/EasyAbp/AbpHelper.CLI)?

**Comment by wakuflair** [comment]
Hi it's added with https://github.com/EasyAbp/Abp.SettingUi/commit/2fcb4df3779f6913cd99cc7e5b11e4d12a89bffc

**Comment by cihangll** [comment]
Thanks.
