### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by cihangll** [EasyAbp/Abp.SettingUi#52]
Hi @wakuflair ,
I'll use this module in my project. Can you release new version?

**Comment by wakuflair** [comment]
I plan to release the new version after ABP 4.1 final, which will be released on January 4, 2021.

**Comment by wakuflair** [comment]
Hi @cihangll 
The new version 1.3.0 has been released, have a try.

**Comment by cihangll** [comment]
Hi @wakuflair, 
İ'll try. Thanks.
