### ISSUE TITLE
The ABP commercial setting management reference this module throw an exception

### ISSUE THREAD

**Issue by viewtance** [EasyAbp/Abp.SettingUi#57]
When using the ABP commercial template reference this module, visit the SettingManagement page, it throw an exception that the "Group1" not in the directory.

I have deleted the branch, so cannot cope the detailed exception info here, if you need it, I could run it again to reproduce it.

**Comment by wakuflair** [comment]
See https://github.com/EasyAbp/Abp.SettingUi/issues/58
