### ISSUE TITLE
KeyNotFoundException: The given key 'Group1' was not present in the dictionary.

### ISSUE THREAD

**Issue by llccig** [EasyAbp/Abp.SettingUi#58]
##错误描述：

KeyNotFoundException: The given key 'Group1' was not present in the dictionary.

##版本：

  1.3.1

##问题分析原因：

调试代码在EasyAbp.Abp.SettingUi.Web.Pages.Components中发现取Group1对应属性值，而SettingInfo并未对Properties进行赋值，导致取值错误。默认是否应该调用WithProperty方法，设置Group1，Group2 的Value?

**Comment by wakuflair** [comment]
Could you provide a sample project to reproduce this issue?

**Comment by llccig** [comment]
![Uploading Snipaste_2021-02-22_15-59-11.png…]()

**Comment by llccig** [comment]
![Snipaste_2021-02-22_16-05-27](https://user-images.githubusercontent.com/58623505/108679639-d0ab6580-7527-11eb-8002-3361c0358264.png)
不知对您是否有帮助，可能我哪里配置错误了？

**Comment by wakuflair** [comment]
@llccig 有能再现的示例工程吗? 我可以下载下来跑的.

**Comment by llccig** [comment]
@wakuflair https://github.com/llccig/TestUI

**Comment by wakuflair** [comment]
@llccig 谢谢你提供的示例工程, 我已成功再现, 查找问题中..
