### ISSUE TITLE
不知道发生了什么，我的abp是4.2.2的mvc 分层的那种，请大佬指点，我是按照配的，各个模块都已经注入了。

### ISSUE THREAD

**Issue by Qianzujin** [EasyAbp/Abp.SettingUi#64]
![image](https://user-images.githubusercontent.com/49854479/113664739-decfd280-96de-11eb-9396-b1cd57cb72a3.png)

**Comment by wakuflair** [comment]
确定SettingUi.Appplication的包已经安装,并且在你的Application模块中DependsOn了?

**Comment by Qianzujin** [comment]
> 确定SettingUi.Appplication的包已经安装,并且在你的Application模块中DependsOn了?

谢谢了 已经解决了
