### ISSUE TITLE
A way to make settings required or default when blank?

### ISSUE THREAD

**Issue by zHaytam** [EasyAbp/Abp.SettingUi#7]
Hello,

First of all, great module! I was just about to make mine and I found yours and used it instead.

I was wondering if there is a way to make settings required? If a user deletes the content of a setting, it will be saved as blank in the DB. This overrides the default value with "nothing".

I see 2 possible solutions:

1. Make settings required, users **must** provide a value.
2. If the user deletes the content of a setting, it's set to the default value instead.

What do you think?  
Thank you!

**Comment by wakuflair** [comment]
Hi @zHaytam 

Thank you for using my module:)

Since ABP setting values can be empty, I think it's better to allow user to pass an empty content from the frontend.

For default values, I'm thinking adding a "Reset to default" button to each group. What's your opinion?

**Comment by gdlcf88** [comment]
Hi @wakuflair 

I think "Reset to default" is a good idea, maybe "Reset" is a better name for the button, because if you delete a setting value, it will inherit from the upstream (ABP calls it "fallback", see: [hikalkan's comment](https://github.com/abpframework/abp/issues/2749#issuecomment-583880316))

And please also add "Inherited" or "Fallback" label to the settings which have no customized value.

**Comment by wakuflair** [comment]
@gdlcf88 
Do you have ideas on how to get the default value of a setting?

**Comment by gdlcf88** [comment]
> If a user deletes the content of a setting, it will be saved as blank in the DB. This overrides the default value with "nothing".

I have a setting item with none-value by default:

![image](https://user-images.githubusercontent.com/30018771/84868542-72340a80-b0af-11ea-8d5b-0b7d36d4cc53.png)

When I use the SettingUI to change another item, the none-value item's value ("") is committed and I can see an extra row in the database:

![image](https://user-images.githubusercontent.com/30018771/84868439-46188980-b0af-11ea-8f48-fb200a044e8c.png)

Unchanged setting items may not need to be committed. What do you think? @wakuflair

**Comment by wakuflair** [comment]
@gdlcf88 
AFAIK, If you provide a default value to your setting, and later you set exactly the default value to it, ABP will delete the record from the setting table.

**Comment by gdlcf88** [comment]
Maybe "Save" buttons for each setting item is a good way to avoid all these problems.
