### ISSUE TITLE
Does this module work well under multi tenancy

### ISSUE THREAD

**Issue by chaoyi996** [EasyAbp/Abp.SettingUi#8]
Hi
First of all, great module! I was just about to make mine and I found yours and used it instead.

I have a problem
Does this module work well under multi tenancy?

I try use this module in multi tenancy,login with tenancy and update setting ,all settings ProviderName are set to 'G' 

Tks

**Comment by chaoyi996** [comment]
I checked the code and found 
` await _settingManager.SetGlobalAsync(name, kv.Value);`
On line 78 of the "SettingUiAppService.cs" file

I think he should be like
`SetForCurrentTenantAsync`

And can you call an event when the user saves the settings? I want to do something after the user saves the settings

Tks

**Comment by wakuflair** [comment]
Hi
Unfortunately SettingUi uses global setting provider for now. Multiple providers support is on the roadmap.

**Comment by chaoyi996** [comment]
I introduced the source code and modified it
Ths

**Comment by Znow** [comment]
@chaoyi996  Then please make a PR for this, so others can use it aswell.

Great module by the way!
