### ISSUE TITLE
Not compatible with version 6.0.2?

### ISSUE THREAD

**Issue by SyPham** [EasyAbp/Abp.SettingUi#80]

**Comment by SyPham** [comment]
Detected package downgrade: Microsoft.Extensions.FileProviders.Embedded from 6.0.2 to 6.0.0

**Comment by gdlcf88** [comment]
https://github.com/EasyAbp/Abp.SettingUi/blob/develop/src/EasyAbp.Abp.SettingUi.Domain.Shared/EasyAbp.Abp.SettingUi.Domain.Shared.csproj#L32
https://github.com/EasyAbp/Abp.SettingUi/blob/develop/src/EasyAbp.Abp.SettingUi.Web/EasyAbp.Abp.SettingUi.Web.csproj#L25

It seems that the package version number is not determined by this module.
