### ISSUE TITLE
Basic Theme NullReferenceException

### ISSUE THREAD

**Issue by Irikale** [EasyAbp/Abp.SettingUi#92]
Hi,
The following error occurs when using basic theme.

NullReferenceException: Object reference not set to an instance of an object.
AspNetCoreGeneratedDocument.Pages_SettingManagement_Index.<ExecuteAsync>b__12_5()

**Comment by gdlcf88** [comment]
What's your ABP version?

**Comment by Irikale** [comment]
6.0.1

**Comment by blackWins** [comment]
#93

**Comment by gdlcf88** [comment]
Please try Setting UI 1.7.1

**Comment by Irikale** [comment]
thanks 👍
